### ISSUE TITLE
Fetchart option causes error

### ISSUE THREAD

**Issue by gryphonmyers** [ageorge/beets-bandcamp#1]
When I enable art: true in my config for bandcamp, I get these errors popping during imports:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.13/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/ui/__init__.py", line 1196, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/ui/commands.py", line 930, in import_func
    import_files(lib, paths, query)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/ui/commands.py", line 907, in import_files
    session.run()
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/importer.py", line 319, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/importer.py", line 1392, in plugin_stage
    func(session, task)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beetsplug/fetchart.py", line 797, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/usr/local/var/pyenv/versions/2.7.13/lib/python2.7/site-packages/beetsplug/fetchart.py", line 859, in art_for_album
    if source.IS_LOCAL or not local_only:
AttributeError: 'BandcampAlbumArt' object has no attribute 'IS_LOCAL'

**Comment by unrblt** [comment]
Hi, sorry for the delay. This should be fixed for `beets v1.4.3` but it will break again in the next version because beetbox/beets@bc582701f changes the signature of `ArtSource.get` again.
