### ISSUE TITLE
Attribute Error fetchart

### ISSUE THREAD

**Issue by japorized** [ageorge/beets-bandcamp#4]
Hi there,

I keep running into this whenever I'm trying to fetch from Bandcamp, hopefully this stack can help you trace the error for a fix:

```shell
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/local/lib/python3.6/site-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.6/site-packages/beets/ui/commands.py", line 934, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python3.6/site-packages/beets/ui/commands.py", line 911, in import_files
    session.run()
  File "/usr/local/lib/python3.6/site-packages/beets/importer.py", line 325, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python3.6/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python3.6/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python3.6/site-packages/beets/importer.py", line 1435, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python3.6/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/fetchart.py", line 793, in fetch_art
    candidate = self.art_for_album(task.album, task.paths, local)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/fetchart.py", line 854, in art_for_album
    source.fetch_image(candidate, self)
  File "/usr/local/lib/python3.6/site-packages/beetsplug/fetchart.py", line 230, in fetch_image
    with closing(self.request(candidate.url, stream=True,
AttributeError: 'str' object has no attribute 'url'
```

Thanks for the hard work on making this plugin.

Edit: Just found that this issue was raised in a closed issue #1

**Comment by unrblt** [comment]
Hi, i'm not sure this is the same issue as #1, let me look into it. Which versions of `beets` and `beets-bandcamp` are you using?

**Comment by japorized** [comment]
Ah I should've added that in my earlier post. Here ya go:

beets version 1.4.5
beets-bandcamp version 0.1.1

**Comment by p3732** [comment]
Having the same issue, created an issue over at beets, because I thought it's fetchart related. It's closed now, but maybe the output there can provide some additional insight: https://github.com/beetbox/beets/issues/2810
